### ISSUE TITLE
Staging backend sporadically fails to initialise

### ISSUE THREAD

**Issue by j-mao** [battlecode/galaxy#403]
Several incidents are generated, with [this one](https://console.cloud.google.com/errors/detail/CPiIyIfykqHpEA?project=mitbattlecode) looking like the root cause. Suspecting something to do with IAM impersonation, but not yet sure.

**Comment by j-mao** [comment]
```
Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/env/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Getting metadata from plugin failed with error: HTTPSConnectionPool(host='iamcredentials.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/-/serviceAccounts/staging-siarnaq-agent@mitbattlecode.iam.gserviceaccount.com:generateAccessToken (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))"
	debug_error_string = "UNKNOWN:Error received from peer secretmanager.googleapis.com:443 {created_time:"2022-12-17T09:18:07.671726774+00:00", grpc_status:14, grpc_message:"Getting metadata from plugin failed with error: HTTPSConnectionPool(host=\'iamcredentials.googleapis.com\', port=443): Max retries exceeded with url: /v1/projects/-/serviceAccounts/staging-siarnaq-agent@mitbattlecode.iam.gserviceaccount.com:generateAccessToken (Caused by SSLError(SSLZeroReturnError(6, \'TLS/SSL connection has been closed (EOF) (_ssl.c:997)\')))"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/env/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: HTTPSConnectionPool(host='iamcredentials.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/-/serviceAccounts/staging-siarnaq-agent@mitbattlecode.iam.gserviceaccount.com:generateAccessToken (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/env/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/env/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/env/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/env/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/env/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/env/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/siarnaq/wsgi.py", line 15, in <module>
    from configurations.wsgi import get_wsgi_application  # noqa: E402
  File "/env/lib/python3.10/site-packages/configurations/wsgi.py", line 8, in <module>
    application = get_wsgi_application()
  File "/env/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/env/lib/python3.10/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/env/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/env/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/env/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/env/lib/python3.10/site-packages/configurations/importer.py", line 176, in load_module
    reraise(err, "Couldn't setup configuration '{0}'".format(cls_path))
  File "/env/lib/python3.10/site-packages/configurations/utils.py", line 65, in reraise
    raise exc
  File "/env/lib/python3.10/site-packages/configurations/importer.py", line 157, in load_module
    cls.pre_setup()
  File "/app/siarnaq/settings.py", line 366, in pre_setup
    _get_secret(
  File "/app/siarnaq/settings.py", line 36, in _get_secret
    return client.access_secret_version(request=request).payload.data
  File "/env/lib/python3.10/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 1503, in access_secret_version
    response = rpc(
  File "/env/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/env/lib/python3.10/site-packages/google/api_core/retry.py", line 205, in retry_target
    raise exceptions.RetryError(
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 Getting metadata from plugin failed with error: HTTPSConnectionPool(host='iamcredentials.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/-/serviceAccounts/staging-siarnaq-agent@mitbattlecode.iam.gserviceaccount.com:generateAccessToken (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

**Comment by j-mao** [comment]
Looks like IAM's `generateAccessToken` RPC is failing. Unsure why, but a few things to note:
- This step is only necessary when running on a local staging. In the real environment, we can skip this step.
- Lazy solution: detect if running on GCE, and skip this step if you are. However, this doesn't explain why this error is happening.
- We're well within quota limits for access token generation requests (at least, it seems for now… maybe the quota listing is lagged). So, quota limits aren't the cause.
